### ISSUE TITLE
System.Reactive.Core assembly: FileNotFoundException in RunnerCommand.Execute?

### ISSUE THREAD

**Issue by bimwood** [StarkBIM/RvtTestRunner#1]
Hi!
Jeremy Tammick suggested I take a look at your project after I posted a question about Unit Testing on Adsk's Revit API Forum. I also took a look at your AU class, of course. You're doing some sophisticated things: I have a fair bit to work through.
However, this is probably something pretty basic: 
1. I've forked and built the RvtTestRunner, 2016 config.
2. I've edited the .addin to point to the .dll.
3. I launch Revit and try to launch the Test Runner.
4. It throws a FileNotFoundException for System.Reactive.Core in RunnerCommand.Execute, line 46:
var testRunnerControlViewModel = new TestRunnerControlViewModel();

There are obviously copies of the Reactive dlls in the bin folder, alongside the dll, but that doesn't seem to be enough. Do I need to install Reactive separately??

StackTrace:
   at RvtTestRunner.UI.TestRunnerControlViewModel..ctor()
   at RvtTestRunner.RunnerCommand.Execute(ExternalCommandData commandData, String& message, ElementSet elements) in C:\Users\dwood\Source\Repos\RvtTestRunner\src\RvtTestRunner\RunnerCommand.cs:line 46

![image](https://user-images.githubusercontent.com/5095961/33799650-d369bbf0-dd27-11e7-8ba6-e17b4f80f780.png)

**Comment by starkcolin** [comment]
Try updating to the latest commit.  You should clean and rebuild the solution as well to ensure the older versions of the DLL files are cleaned out.
If that doesn't work, check the version of the System.Reactive.Core DLL and let me know what it says (Windows Explorer properties -> Details tab)

**Comment by bimwood** [comment]
Thanks Colin: That looks fixed to me:
![image](https://user-images.githubusercontent.com/5095961/33806658-5eaa972a-ddc3-11e7-9078-42a852e0c74e.png)

**Comment by starkcolin** [comment]
OK great. Closing
